name: Feature Branch

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install project dependencies
        run: |
          uv sync --all-extras --dev

      - name: Lint with Ruff
        run: make lint

      - name: Type Check with Mypy
        run: make type-check

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install project dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run Unit Tests
        run: make all-test

  # Tests PR as it was already merged:
  test-merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && github.event.pull_request.mergeable_state != 'dirty'

    permissions:
      contents: read
      issues: read
      pull-requests: write

    steps:
      - name: Checkout merged PR commit
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install project dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run Unit Tests
        run: make all-test